FROM openjdk:11-jre-slim
MAINTAINER reiiissamuel@gmail.com
WORKDIR /usr/app
COPY hermodr-1.0-SNAPSHOT-jar-with-dependencies.jar /usr/app/hermodr-1.0-SNAPSHOT-jar-with-dependencies.jar
EXPOSE 8085
CMD java -jar hermodr-1.0-SNAPSHOT-jar-with-dependencies.jar
